In [1]:
import psycopg2
# Connect to an existing database
conn = psycopg2.connect("dbname='bt' user='postgres' host='localhost' password='severo' port='5432'")

# Open a cursor to perform database operations
cur = conn.cursor()

# Execute a command: this creates a new table
cur.execute("select tid,time,edge_id from matched_tracks order by tid,time asc")
bd = cur.fetchall()
cur.execute("select distinct edge_id from matched_tracks order by edge_id asc")
bt = cur.fetchall()

# Pass data to fill a query placeholders and let Psycopg perform
# the correct conversion (no more SQL injections!)
#>>> cur.execute("INSERT INTO test (num, data) VALUES (%s, %s)",
#...      (100, "abc'def"))

# Query the database and obtain data as Python objects
#>>> cur.execute("SELECT * FROM test;")
#>>> cur.fetchone()
#(1, 100, "abc'def")

# Make the changes to the database persistent
#>>> conn.commit()

# Close communication with the database
cur.close()

conn.close()
print("Finished")

Finished


In [2]:
l=list()
r=list()
j=1
for i in bd:
    if i[0]==j:
        r.append(i)
    else:
        l.append(r)
        r=list()
        r.append(i)
        j=j+1
l.append(r)
print("finished")


finished


In [3]:
t=list()
for i in bt:
    t.append(i[0])
dicionario=dict()
q=0
for i in t:
    dicionario[i]=q
    q=q+1
print("Finished")

Finished


In [4]:
import numpy as np
k=len(t)
c =np.zeros( (k,k),dtype=np.int32)

In [5]:
for s in l:
    y=len(s)
    for o in range(0,y-2):
        if s[o][2] != s[o+1][2]:
            d1=dicionario[s[o][2]]
            d2=dicionario[s[o+1][2]]
            c[d1][d2]=c[d1][d2]+1

In [6]:
def verifica(c):
    for m in c:
        for n in m:
            if n >= 0:
                return True;
    return False

def verifica2(m,f):
    for i in range(0,len(f)-1):
        

[[0 2 0 ... 0 0 0]
 [0 0 2 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 2 0]
 [0 0 0 ... 0 0 2]
 [0 0 0 ... 0 0 0]]


In [10]:
dicionario2 = dict()
for i in t:
    d=dicionario[i]
    dicionario2[d]=i

In [11]:
def phase_1(t,m,e,a,d2):
    O=set()
    k=0
    C=list()
    while verifica(m):
        k=k+1
        ind = np.unravel_index(np.argmax(c, axis=None), c.shape)
        d=ind[0]
        f=ind[1]
        Sd=d2[d]
        Sf=d2[f]
        C.append([Sd,Sf])
        if m[d][f]>0:
            m[d][f]=-1*(m[d][f])
        else:
            m[d][f]=-1
        while(verifica2(m)):

In [13]:
print(dicionario)

{0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 16: 7, 17: 8, 18: 9, 19: 10, 20: 11, 21: 12, 22: 13, 23: 14, 24: 15, 25: 16, 26: 17, 27: 18, 28: 19, 29: 20, 30: 21, 31: 22, 37: 23, 38: 24, 39: 25, 40: 26, 42: 27, 44: 28, 50: 29, 51: 30, 52: 31, 53: 32, 54: 33, 55: 34, 56: 35, 57: 36, 58: 37, 59: 38, 61: 39, 66: 40, 67: 41, 68: 42, 69: 43, 70: 44, 71: 45, 72: 46, 73: 47, 74: 48, 75: 49, 76: 50, 77: 51, 78: 52, 101: 53, 102: 54, 103: 55, 104: 56, 105: 57, 106: 58, 107: 59, 108: 60, 109: 61, 110: 62, 111: 63, 112: 64, 113: 65, 114: 66, 115: 67, 116: 68, 117: 69, 118: 70, 119: 71, 120: 72, 121: 73, 122: 74, 123: 75, 124: 76, 125: 77, 126: 78, 127: 79, 128: 80, 129: 81, 130: 82, 131: 83, 132: 84, 133: 85, 134: 86, 135: 87, 136: 88, 137: 89, 138: 90, 139: 91, 140: 92, 141: 93, 142: 94, 143: 95, 144: 96, 145: 97, 146: 98, 148: 99, 149: 100, 150: 101, 151: 102, 152: 103, 153: 104, 154: 105, 155: 106, 157: 107, 158: 108, 159: 109, 160: 110, 161: 111, 162: 112, 163: 113, 164: 114, 165: 115, 166: 116,

In [18]:
print(len(c[9]))

18655
