In [4]:
# Criando a matriz de transições:
import numpy as np
m =np.zeros( (5,5),dtype=np.int32)

In [27]:
m[0][0]  =0
m[0][1]  =10
m[0][2]  =10
m[0][3]  =10
m[0][4]  =12
m[1][0]  =1
m[1][1]  =0
m[1][2]  =1
m[1][3]  =10
m[1][4]  =1
m[2][0]  =1
m[2][1]  =1
m[2][2]  =0
m[2][3]  =1
m[2][4]  =1
m[3][0]  =1
m[3][1]  =10
m[3][2]  =1
m[3][3]  =0
m[3][4]  =1
m[4][0]  =10
m[4][1]  =10
m[4][2]  =10
m[4][3]  =11
m[4][4]  =0

In [22]:
print(m)

[[ 0 10 10 10 11]
 [ 1  0  1 10  1]
 [ 1  1  0  1  1]
 [ 1 10  1  0  1]
 [10 10 10 11  0]]


In [24]:
dicionario2=dict()
for i in range(0,5):
    dicionario2[i]=i
dicionario3=dict()
for i in range(0,5):
    for j in range(0,5):
        dicionario3[(i,j)] = (i,j)

In [8]:
def not_marked(m,a):
    for n in m:
        for i in n:
            if i > 0 and i>=a:
                return True
    return False

def maximo(m,c):
    l=0
    f=0
    for i in range(0,c):
        for j in range(0,c):
            if m[i][j]>m[l][f]:
                l=i
                f=j
    return [l,f]

def marking(a):
    if a>0:
        return -1*a
    return a

def not_marked_2(m,d,f,a,e,c):
    u=-1
    minimo=100000
    for i in range(0,c):
        if m[f][i]>=a:
            t = m[d][f]
            if t<0:
                t=t*(-1)
            if abs(t-m[f][i]) < minimo and abs(t-m[f][i])<=e:
                minimo = abs(t-m[f][i])
                u=i
    return u

def not_marked_3(m,d,f,a,e,c):
    u=-1
    minimo=1000000
    for i in range(0,c):
        if m[i][d]>=a:
            t = m[d][f]
            if t<0:
                t=t*(-1)
            if abs(t-m[u][d])<minimo and abs(t-m[u][d])<=e:
                minimo=abs(t-m[u][d])
                u=i
    return u

In [36]:
def netscan_phase_1(dicionario3,c,dicionario2,m,e,a):
    O=set()
    k=0
    C=list()
    while not_marked(m,a):
        indices=maximo(m,c)
        d=indices[0]
        f=indices[1]
        tupla=dicionario3[(d,f)]
        Sd=dicionario2[tupla[0]]
        print("Sd: ",Sd)
        Sf=dicionario2[tupla[1]]
        print("Sf: ",Sf)
        C.append([Sd,Sf])
        m[d][f]=marking(m[d][f])
        u=not_marked_2(m,d,f,a,e,c)
        while u>-1:
            print("1")
            tupla=dicionario3[(f,u)]
            Su=dicionario2[tupla[1]]
            print("Su :",Su)
            C[k].append(Su)
            m[f][u]=marking(m[f][u])
            d=f
            f=u
            u=not_marked_2(m,d,f,a,e,c)
        u=not_marked_3(m,d,f,a,e,c)
        while u>-1:
            print("2")
            tupla=dicionario3[(u,d)]
            Su=dicionario2[tupla[0]]
            print("Su :",Su)
            C[k] = [Su]+C[k]
            m[u][d]=marking(m[u][d])
            f=d
            d=u
            u=not_marked_3(m,d,f,a,e,c)
        k=k+1
    return C

In [38]:
C=netscan_phase_1(dicionario3,5,dicionario2,m,2,10)

Sd:  0
Sf:  4
1
Su : 3
1
Su : 1
1
Su : 3
2
Su : 0
2
Su : 4
Sd:  0
Sf:  2
Sd:  0
Sf:  3
Sd:  4
Sf:  1
Sd:  4
Sf:  2


In [39]:
print(C)

[[4, 0, 0, 4, 3, 1, 3], [0, 2], [0, 3], [4, 1], [4, 2]]


In [37]:
for i in range(0,5):
    for j in range(0,5):
        if m[i][j]<0:
            m[i][j]= m[i][j]*(-1)

In [33]:
print(m)

[[  0 -10 -10 -10 -12]
 [  1   0   1 -10   1]
 [  1   1   0   1   1]
 [  1 -10   1   0   1]
 [-10 -10 -10 -11   0]]
